module.exports = {
  docs: [
    {
      type: "category",
      label: "Developer Guidelines",
      items: [
        "open-source-guidelines",
        "engineering-culture",
        "agile-methodologies",
        "pair-mob-programming",
        "developer-tools",
        "developer-tools-ux-ui",
        "open-source-projects",
        "boilerplate",
        "material-ui",
        "visual-resources",
        "social-media-guidelines",
        "devops",
      ],
    },
    {
      type: "category",
      label: "Learn EOSIO",
      items: [
        "eos-learn/eosio-protocol",
        "eos-learn/consensus-mechanism",
        "eos-learn/system-resources",
        "eos-learn/eosio-components",
        "eos-learn/accounts-and-permissions",
        "eos-learn/important-functions",
        "eos-learn/private-keys",
        "eos-learn/dapp-development",
        "eos-learn/eos-blockchain",
        "eos-learn/smart-contract",
        "eos-learn/ricardian-contracts",
        "eos-learn/blockchain-security",
        "eos-learn/nfts-on-eosio",
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      items: [
        "tutorials/markdown-guide",
        "tutorials/git-workflow-tutorial",
        "tutorials/github-guide",
        "tutorials/github-keys",
        "tutorials/react-tutorial",
        "tutorials/graphql-tutorial",
        "tutorials/docker",
        "tutorials/kubernetes",
        "tutorials/node-installation",
        "tutorials/private-network-installation",
        "tutorials/hello-world-contract",
        "tutorials/how-to-publish-packages",
        "tutorials/modern-cpp",
      ],
    },
    {
      type: "category",
      label: "Tools",
      items: [
        "tools/glossary",
        "tools/command-line",
        "tools/nodeos-command-line-reference",
        "tools/block-explorers",
        "tools/eosio-sdk-libraries",
        "tools/readme-file-template",
        "tools/frequently-asked-questions",
      ],
    },
    {
      type: "category",
      label: "Community Resources",
      items: [
        "community-resources/eosio-networks",
        "community-resources/telegram-channels",
        "community-resources/blog-posts",
        "community-resources/eos-podcasts",
        "community-resources/useful-links",
      ],
    },
  ],
};
